### ISSUE TITLE
Creation of specification for defining scenarios

### ISSUE THREAD

**Issue by NektariosFifes** [asyncapi/fluffy-robot#10]
#### Reason/Context

- Scenarios will be files that the user will be able to configure the library to distribute the load of the simulation based on his needs

A file parser will be made. This issue however is for creating the specification of the 'scenario-file'.

Pull request #11

**Comment by AceTheCreator** [comment]
@NektariosFifes Please reach out to me when you need my attention

**Comment by NektariosFifes** [comment]
@AceTheCreator Sorry for being inactive. I have studying design patterns and trying to make sure the library start on correct footing. I am rewriting parts of the code  trying to figure out how to make it modular. I will contact you.

**Comment by NektariosFifes** [comment]
solved in #5
