### ISSUE TITLE
First public community meeting - Monday 19. April - 7:30 AM UTC

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/fluffy-robot#2]
Since we have quite a few people wanting to help out in the development of the library I thought it was in order to hold a public meeting which should clarify the development of the library and how we are to collaborate on it.

The meeting will take place [Monday 19. April - 7:30 AM UTC](https://everytimezone.com/s/9f250524)
- Zoom link: https://postman.zoom.us/j/89392863142

The meeting will be recorded and uploaded to the AsyncAPI youtube channel to ensure those who cannot join that time can follow along as well. Any decisions will be added to issues in the repository so they can be discussed further if needed.

## Attendees
@AceTheCreator
@NektariosFifes
@jonaslagoni 

## Notes:
- Focus on modularity, but keeping in a way that it does not dig us down a rabbit hole.
- Focus on CLI more than frontend from the start
- We are gonna keep track of the project using GitHub's projects page - https://github.com/asyncapi/fluffy-robot/projects/1
- @NektariosFifes are gonna create some more overall issues such as for the CLI, React library (already done), etc.
- I am gonna figure out some permission settings in terms of code owners

Did I miss something?

## Recording
https://youtu.be/CjVZIyse2k4

**Comment by jonaslagoni** [comment]
I would suggest we add an agenda next time to keep it more structured, what do you guys think? 

cc. @AceTheCreator, @NektariosFifes

**Comment by AceTheCreator** [comment]
> I would suggest we add an agenda next time to keep it more structured, what do you guys think?
> 
> cc. @AceTheCreator, @NektariosFifes
You're absolutely right @jonaslagoni

**Comment by derberg** [comment]
Here is the recording -> https://youtu.be/CjVZIyse2k4

**Comment by jonaslagoni** [comment]
> Here is the recording -> https://youtu.be/CjVZIyse2k4

Thanks @derberg!
