### ISSUE TITLE
Request Handler Creation 

### ISSUE THREAD

**Issue by NektariosFifes** [asyncapi/fluffy-robot#21]
It should  be able to take an object provided by  simPlotMapper  and conduct  requests to the specified routes with corresponding body and  headers. 
Prerequirement #18

**Comment by jonaslagoni** [comment]
Remember that we have different kind of protocols that the simulation logic needs to handle, not just HTTP, therefore there must be some kind of abstraction in this layer.

**Comment by jonaslagoni** [comment]
Solved in https://github.com/asyncapi/fluffy-robot/pull/34
