### ISSUE TITLE
Create the link between asyncApi spec file and simPlot file

### ISSUE THREAD

**Issue by NektariosFifes** [asyncapi/fluffy-robot#22]
There needs to be an extension for the async-api file so that you can link routes from the async api file with corresponding Plots which are going to define details about how the application simulation should occur.

Status: working on it

**Comment by AceTheCreator** [comment]
@jonaslagoni  @NektariosFifes is this now under GSOC???

**Comment by jonaslagoni** [comment]
> @jonaslagoni @NektariosFifes is this now under GSOC???

@AceTheCreator It is yes 😄

**Comment by AceTheCreator** [comment]
Ok :+1:

**Comment by NektariosFifes** [comment]
implementation in #27
