### ISSUE TITLE
Should i use babel and ecmascript or commonjs?

### ISSUE THREAD

**Issue by NektariosFifes** [asyncapi/fluffy-robot#9]
#### Reason/Context
Please try answering few of those questions
- Which option do you suggest and why?

**Comment by AceTheCreator** [comment]
@NektariosFifes I'd suggest you use babel and ECMAScript. @jonaslagoni what do you think?

**Comment by jonaslagoni** [comment]
I don't mind if you use babel and ECMAScript, keep in mind that if there is a use-case for others to integrate a library into another Node application that the output of the transpilation process has to be CommonJS, but I don't think we are gonna have a problem changing it later anyway 🤔 .

**Comment by NektariosFifes** [comment]
https://auth0.com/blog/javascript-module-systems-showdown/
we will probably not need any code splitting or asynchronous imports. These features are very useful but probably not in our case. I will continue using commons.js then. Simpler and no  need to use babel.
